language: cpp
compiler:
  - gcc
  - clang

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-5
    - g++-5

before_install:
  - sudo apt-get update
#  - sudo apt-cache search tinyxml
  - sudo apt-get install -y liblua5.1-0-dev zlib1g-dev libsqlite3-dev libtinyxml-dev
# lua-sql-sqlite3 lua-svn mailutils mutt libtinyxml-dev

script:
  - make lua51
