#!/bin/sh

CMDRES=$(localedef --list-archive | grep "ru_RU.cp1251")

if [ "_$CMDRES" = "_" ]; then
	echo "Please run following command as super user: localedef -c -i ru_RU -f CP1251 ru_RU.CP1251"
else
	LANG=ru_RU.CP1251
	export LUA_PATH="/home/dc/src/PtokaX/scripts/libs/?.lua;;"
	./PtokaX
	#sudo valgrind --leak-check=full --leak-resolution=med --log-file=valgrind-log-file.log --time-stamp=yes ./PtokaX
fi
