#!/bin/sh
#su dc --shell /bin/bash --command "ulimit -n 32768"
# Fix /etc/security/limits.conf
# dc soft nofile 20480
# dc hard nofile 20480
#
LANG=ru_RU.CP1251
export LUA_PATH='/home/dc/src/PtokaX/scripts/libs/?.lua;;'
./PtokaX
#sudo valgrind --leak-check=full --leak-resolution=med --log-file=valgrind-log-file.log --time-stamp=yes ./PtokaX
